[versions]
# Android & Project
agp = "8.4.2"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
compileSdk = "34"
minSdk = "26"
targetSdk = "34"

# Compose
composeBom = "2024.04.00"
composeCompiler = "1.5.14"
activityCompose = "1.9.0"
material3 = "1.2.1"
materialIcons = "1.6.8"

# Lifecycle & Coroutines
lifecycle = "2.8.3"
coroutines = "1.8.1"

# CameraX
camerax = "1.3.4"

# ML & TFLite
mlkitObjectDetection = "17.0.1"
tfliteSupport = "0.4.4"
tfliteSelectOps = "2.15.0"

# Room
room = "2.6.1"

# Utility
accompanistPermissions = "0.36.0"
coil = "2.4.0"
gson = "2.10.1"
material = "1.12.0"

[libraries]
# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }

# Lifecycle & Coroutines
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
kotlinx-coroutines-playservices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# CameraX
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }

# ML & TFLite
google-mlkit-obj-detection = { group = "com.google.mlkit", name = "object-detection", version.ref = "mlkitObjectDetection" }
tensorflow-lite-select-tf-ops = { group = "org.tensorflow", name = "tensorflow-lite-select-tf-ops", version.ref = "tfliteSelectOps" }
tensorflow-lite-support = { group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "tfliteSupport" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Utility
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }